### ISSUE TITLE
Trying to load the plugin ends with error

### ISSUE THREAD

**Issue by Maddimax** [mprivat/mkdocs-snippet-plugin#1]
INFO    -  Building documentation...
ERROR   -  Config value: 'markdown_extensions'. Error: Failed to initiate extension 'snippet': module 'snippet' has no attribute 'makeExtension'

mkdocs version is 1.0.4, python is 3.7

**Comment by mprivat** [comment]
That's probably because you're defining it under markdownExtensions in mkdocs.yml. It needs to be under `plugins`:

```
plugins:
    - snippet:
          base_path: docs
```

> INFO - Building documentation...
> ERROR - Config value: 'markdown_extensions'. Error: Failed to initiate extension 'snippet': module 'snippet' has no attribute 'makeExtension'
> 
> mkdocs version is 1.0.4, python is 3.7
