### ISSUE TITLE
Include snippets from any file, not just .md

### ISSUE THREAD

**Issue by paulcwarren** [mprivat/mkdocs-snippet-plugin#4]
I would like to keep my mkdocs up-to-date with the latest code and therefore I would like to inject code snippets (java in my case), not just .md snippets.  So, something like:-

```
{{ snippet('git@github.com:myrepo/mkdocs-snippet-plugin.git', '/some/path/to/myfile.java', '10-24') }}
```

where 10-24 means inject lines 10-24 of /some/path/to/myfile.java.

I assume this is not possible at the moment.  But it would be very nice if your plugin could do it.

**Comment by mprivat** [comment]
I'm not sure how good that use case would be though. I get what you're thinking of doing but if you add just one line of code or comment to your Java file, all the sudden your doc will be wrong. Or if you change your code formatter for example.
