### ISSUE TITLE
Package PyPI

### ISSUE THREAD

**Issue by SamazoOo** [mprivat/mkdocs-snippet-plugin#5]
Hello,

Did you update the package in PyPI?

I see here that you fix an error here in GitHub, but when I install the package from PyPI don't.

<img width="1579" alt="image" src="https://user-images.githubusercontent.com/17595240/80911115-9bcde800-8d34-11ea-8af0-eae63c233569.png">

**Comment by enlivendreamer** [comment]
I'm running into the same issue. @SamazoOo How did you get around this ?

**Comment by mprivat** [comment]
I just uploaded the latest to pypi

**Comment by enlivendreamer** [comment]
Thanks @mprivat

**Comment by enlivendreamer** [comment]
@mprivat  I don't see 1.0.2 show up in [PyPi](https://pypi.org/project/mkdocs-snippet-plugin/) yet.

**Comment by mprivat** [comment]
It was my bad, I didn't pay attention to an error while uploading. It should be straight now.

**Comment by enlivendreamer** [comment]
Thanks @mprivat !
